### ISSUE TITLE
Unsupported operation: Cannot set value in unmodifiable Map

### ISSUE THREAD

**Issue by cuberob** [aloisdeniel/flutter_sheet_localization#20]
Hi there!
The plugin looks great, but when trying to launch the app after adding the `AppLocalizationsDelegate()` i'm getting the following error.

Stacktrace:
```
I/flutter (13176): Unsupported operation: Cannot set value in unmodifiable Map
I/flutter (13176): 
I/flutter (13176): The relevant error-causing widget was:
I/flutter (13176):   MaterialApp file:///.../lib/app.dart:26:14
I/flutter (13176): 
I/flutter (13176): When the exception was thrown, this was the stack:
I/flutter (13176): #0      _ImmutableMap.[]= (dart:core-patch/immutable_map.dart:76:5)
I/flutter (13176): #1      initializeDateFormattingCustom (package:intl/date_symbol_data_custom.dart:35:19)
I/flutter (13176): #2      loadDateIntlDataIfNotLoaded.<anonymous closure> (package:flutter_localizations/src/utils/date_localizations.dart:43:9)
I/flutter (13176): #3      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:288:8)
I/flutter (13176): #4      _ImmutableMap.forEach (dart:core-patch/immutable_map.dart:45:8)
I/flutter (13176): #5      CastMap.forEach (dart:_internal/cast.dart:287:13)
I/flutter (13176): #6      loadDateIntlDataIfNotLoaded (package:flutter_localizations/src/utils/date_localizations.dart:26:8)
I/flutter (13176): #7      _MaterialLocalizationsDelegate.load.<anonymous closure> (package:flutter_localizations/src/material_localizations.dart:607:7)
I/flutter (13176): #8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
I/flutter (13176): #9      _MaterialLocalizationsDelegate.load (package:flutter_localizations/src/material_localizations.dart:606:32)
I/flutter (13176): #10     _loadAll (package:flutter/src/widgets/localizations.dart:58:49)
I/flutter (13176): #11     _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:509:62)
I/flutter (13176): #12     _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:474:5)
I/flutter (13176): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
I/flutter (13176): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (13176): ...     Normal element mounting (102 frames)
I/flutter (13176): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (13176): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (13176): #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (13176): #119    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:397:11)
I/flutter (13176): #120    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (13176): #121    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (13176): #122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (13176): ...     Normal element mounting (7 frames)
I/flutter (13176): #129    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
I/flutter (13176): ...     Normal element mounting (7 frames)
I/flutter (13176): #136    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
I/flutter (13176): ...     Normal element mounting (7 frames)
I/flutter (13176): #143    _NestedHookElement.mount (package:nested/nested.dart:188:11)
I/flutter (13176): #144    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (13176): #145    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (13176): #146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (13176): #147    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:397:11)
I/flutter (13176): #148    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (13176): #149    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (13176): #150    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (13176): ...     Normal element mounting (7 frames)
I/flutter (13176): #157    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
I/flutter (13176): ...     Normal element mounting (7 frames)
I/flutter (13176): #164    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
I/flutter (13176): ...     Normal element mounting (7 frames)
I/flutter (13176): #171    _NestedHookElement.mount (package:nested/nested.dart:188:11)
I/flutter (13176): #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (13176): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (13176): #174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (13176): #175    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:397:11)
I/flutter (13176): #176    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (13176): #177    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (13176): #178    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (13176): ...     Normal element mounting (7 frames)
I/flutter (13176): #185    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
I/flutter (13176): ...     Normal element mounting (7 frames)
I/flutter (13176): #192    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
I/flutter (13176): ...     Normal element mounting (7 frames)
I/flutter (13176): #199    _NestedHookElement.mount (package:nested/nested.dart:188:11)
I/flutter (13176): ...     Normal element mounting (7 frames)
I/flutter (13176): #206    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
I/flutter (13176): ...     Normal element mounting (23 frames)
I/flutter (13176): #229    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (13176): #230    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (13176): #231    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
I/flutter (13176): #232    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
I/flutter (13176): #233    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
I/flutter (13176): #234    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter (13176): #235    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
I/flutter (13176): #236    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
I/flutter (13176): #237    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
I/flutter (13176): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

And the output of flutter doctor:

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-NL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.47.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

Any thoughts?

**Comment by cuberob** [comment]
Looks like the issue is caused by
```
GlobalMaterialLocalizations.delegate,
GlobalWidgetsLocalizations.delegate,
```
Excluding these for now seems to fix the issue.

Cheers!
